// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLBlazorApp1ML.Model
{
    public class ModelInput
    {
        [ColumnName("A"), LoadColumn(0)]
        public float A { get; set; }


        [ColumnName("B"), LoadColumn(1)]
        public float B { get; set; }


        [ColumnName("C"), LoadColumn(2)]
        public float C { get; set; }


        [ColumnName("D"), LoadColumn(3)]
        public float D { get; set; }


        [ColumnName("E"), LoadColumn(4)]
        public string E { get; set; }


    }
}
